DROP DATABASE polytech;
DROP DATABASE medical;
DROP DATABASE polytech_staraya_russa; 
DROP DATABASE SPO_IZEUS;
DROP DATABASE SPO_IYUR;
DROP DATABASE SPO_INPO;

CREATE DATABASE polytech;
CREATE DATABASE medical;
CREATE DATABASE polytech_staraya_russa; 
CREATE DATABASE SPO_IZEUS;
CREATE DATABASE SPO_IYUR;
CREATE DATABASE SPO_INPO;
